BossPlayerSpawnLocation:
  worldName:
  x:
  y:
  z:
BossSpawnLocation:
  worldName:
  x:
  y:
  z:
#Base for maps stuff
#Just for the sake of visualization
Maps:
  Volcanic:
    worldName: Volcanic
    middle: 0,60,0
    RedSpawns:
      - Volcano,0,100,0
      - Volcano,10,100,0
      - Volcano,0,100,-10
    BlueSpawns:
      - Volcano,0,100,0
      - Volcano,10,100,0
      - Volcano,0,100,-10
    GreenSpawns:
      - Volcano,0,100,0
      - Volcano,10,100,0
      - Volcano,0,100,-10
    YellowSpawns:
      - Volcano,0,100,0
      - Volcano,10,100,0
      - Volcano,0,100,-10
    EntitySpawns:
      - Volcano,5,100,0
      - Volcano,15,100,0
      - Volcano,5,100,-5
    BridgePoints:
      - Volcanic,1,100,67,100 #World name, bridge segment, x, y, z
    Chests:
      - Volcanic,100,67,100 #World name, x, y, z